# Etapa 1: Build da aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Hackaton.Web/Hackaton.Web.csproj", "Hackaton.Web/"]
COPY . .

WORKDIR "/src/Hackaton.Web"
RUN dotnet publish "Hackaton.Web.csproj" -c Release -o /app/publish

# Etapa 2: Imagem final para servir com NGINX
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

# Remove conteúdo padrão do NGINX
RUN rm -rf ./*

# Copia os arquivos compilados do Blazor WebAssembly
COPY --from=build /app/publish/wwwroot .

# Remove configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copia sua configuração personalizada renomeando para default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# (Opcional) Exibir arquivos da conf.d para depuração
# RUN ls -la /etc/nginx/conf.d