# Build da aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Hackaton.Web/Hackaton.Web.csproj", "Hackaton.Web/"]
COPY . .

WORKDIR "/src/Hackaton.Web"
RUN dotnet publish "Hackaton.Web.csproj" -c Release -o /app/publish

# Imagem para servir arquivos estáticos
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

# Remove conteúdo padrão do NGINX
RUN rm -rf ./*

# Copia os arquivos compilados do Blazor WebAssembly
COPY --from=build /app/publish/wwwroot .

# Remove configuração default do nginx (opcional)
RUN rm /etc/nginx/conf.d/default.conf

# Adiciona uma configuração customizada para fallback do Blazor
COPY nginx.conf /etc/nginx/conf.d
