FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Hackaton.Web/Hackaton.Web.csproj", "Hackaton.Web/"]
RUN dotnet restore "Hackaton.Web/Hackaton.Web.csproj"
COPY . .
WORKDIR "/src/Hackaton.Web"
RUN dotnet build "Hackaton.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Hackaton.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Hackaton.Web.dll"] 