apiVersion: v1
kind: Service
metadata:
  name: hackaton-api-service
  labels:
    app: hackaton
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: hackaton
    tier: backend 