apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-pvc
  labels:
    app: hackaton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 