apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:  
  - configmap.yaml
  - secret.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - web-configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-hpa.yaml
  - ingress.yaml

namespace: hackaton 