apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: hackaton
    tier: frontend
data:
  nginx.conf: |
    server {
      listen 5050;
      server_name localhost;

      root /usr/share/nginx/html;
      index index.html;

      location / {
          try_files $uri $uri/ /index.html;
      }

      # Permite comunicação com API
      location /api {
          proxy_pass http://hackaton-api-service:5000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
    } 