apiVersion: v1
kind: Service
metadata:
  name: hackaton-web-service
  labels:
    app: hackaton
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hackaton
    tier: frontend 