apiVersion: v1
kind: Service
metadata:
  name: hackaton-web-service
  labels:
    app: hackaton
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: hackaton
    tier: frontend 